coffeedapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'', include('core.urls')),
                       )

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import core.views as coreviews
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    url(r'^$', coreviews.LandingView.as_view()),
    url(r'location/$', coreviews.LocationListView.as_view()),
   	url(r'search/$', coreviews.SearchListView.as_view()),
    url(r'location/(?P<pk>\d+)/detail/$', login_required(coreviews.LocationDetailView.as_view()), name='location_list'),
    #url(r'location/create/$', login_required(coreviews.LocationCreateView.as_view())),
    #url(r'location/(?P<pk>\d+)/update/$', login_required(coreviews.LocationUpdateView.as_view()), name='location_update'),
    #url(r'location/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name='review_create'),
    #url(r'location/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name='review_update'),\
    url(r'entrance/$', coreviews.entrance),
    #url(r'login/$', auth_views.login, {'template_name': 'base/entrance.html'}),
    url('^logout/', auth_views.logout, {'next_page': '/'})
)

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
# from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField

import os
import uuid


def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

RATING_CHOICES = (
    (0, 'None'),
    (1, '*'),
    (2, '**'),
    (3, '***'),
    (4, '****'),
    (5, '*****'),
)

YESNO_CHOICES = (
    (0, 'No'),
    (1, 'Yes')
)

SUBURB_CHOICES = (
    (0, 'Botley'),
    (1, 'Central'),
    (2, 'Cowley'),
    (3, 'Headington'),
    (4, 'Jericho'),
    (5, 'Summertown')
)

WIFI_CHOICES = (
    (0, 'None Available'),

    (1, 'Sometimes Ok'),
    (3, 'Strong')
)

PLURAL_CHOICES = (
    (0, 'None'),
    (1, 'Minimal'),
    (2, 'Some'),
    (3, 'Ample')
)


def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)


# Create your models here.
class Location(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    position = GeopositionField(null=True, blank=True)
    area = models.IntegerField(choices=SUBURB_CHOICES, null=True, blank=True)
    hours = models.TextField(null=True, blank=True)
    seating = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    wifi = models.IntegerField(choices=WIFI_CHOICES, null=True, blank=True)
    outdoor = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)
    fb_page = models.URLField(null=True, blank=True)
    fb_page_label = models.CharField(max_length=128, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname="location_list", args=[self.id])

    # def get_average_rating(self):
    # average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
    # if average == None:
    #	return average
    # else:
    #	return int(average)

    # def get_reviews(self):
    # return self.review_set.all()

# class Review(models.Model):
#	location = models.ForeignKey(Location)
#	user = models.ForeignKey(User)
#	description = models.TextField(null=True, blank=True)
#	rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
#	created_at = models.DateTimeField(auto_now_add=True)

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
#from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect
from sitegate.decorators import redirect_signedin, sitegate_view, signup_view

import core.models as coremodels


class LandingView(TemplateView):
    template_name = 'base/index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('/location')

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class LocationListView(ListView):
    model = coremodels.Location
    template_name = 'location/list.html'
    paginate_by = 8


class LocationDetailView(DetailView):
    model = coremodels.Location
    template_name = 'location/detail.html'
    context_object_name = 'location'

    def get_context_data(self, **kwargs):
        context = super(LocationDetailView, self).get_context_data(**kwargs)

        context.update({'fb_like_url': self.request.build_absolute_uri(self.request.path)})

        return context

    #  def get_context_data(self, **kwargs):
    #     context = super(LocationDetailView, self).get_context_data(**kwargs)
    #    location = coremodels.Location.objects.get(id=self.kwargs['pk'])
    #   if self.request.user.is_authenticated():
    #      user_reviews = coremodels.Review.objects.filter(location=location, user=self.request.user)
    #     if user_reviews.count() > 0:
    #        context['user_review'] = user_reviews[0]
    #   else:
    #      context['user_review'] = None

#        return context


class SearchListView(LocationListView):

    def get_queryset(self):
        queryset = self.model.objects.all()
        incoming_query_string = self.request.GET.get('query', '')
        incoming_area = self.request.GET.get('category', '')

        if incoming_query_string:
            queryset = queryset.filter(title__icontains=incoming_query_string)
        if incoming_area:
            queryset = queryset.filter(area=incoming_area)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        category = self.request.GET.get('category')
        category_val = None

        if category or category != 0:
            category_choice_dict = dict((str(x), y) for x, y in coremodels.SUBURB_CHOICES)
            category_val = category_choice_dict.get(category)

        context.update({'query': self.request.GET.get('query'),
                        'category': category_val})

        return context

    #class LocationCreateView(CreateView):
    #	model = coremodels.Location
    #	template_name = 'base/form.html'
    #	fields = "__all__"

    #class LocationUpdateView(UpdateView):
    #   model = coremodels.Location
    #  template_name = 'base/form.html'
    # fields = "__all__"

    #class ReviewCreateView(CreateView):
    #   model = coremodels.Review
    #  template_name = 'base/form.html'
    # fields =['description', 'rating']

    #def form_valid(self, form):
    #   form.instance.user = self.request.user
    #  form.instance.location = coremodels.Location.objects.get(id=self.kwargs['pk'])
    # return super(ReviewCreateView, self).form_valid(form)

    #def get_success_url(self):
    #   return self.object.location.get_absolute_url()

    #class ReviewUpdateView(UpdateView):
    #   model = coremodels.Review
    #  template_name = 'base/form.html'
    # fields =['description', 'rating']

    #    def get_object(self):
    #       return coremodels.Review.objects.get(location__id=self.kwargs['pk'], user=self.request.user)

    # def get_success_url(self):
    #    return self.object.location.get_absolute_url()


@sitegate_view(widget_attrs={'class': 'form-control', 'placeholder': lambda f: f.label}, template='form_bootstrap3') # This also prevents logged in users from accessing our sign in/sign up page.
def entrance(request):
    return render(request, 'base/entrance.html', {'title': 'Sign in & Sign up'})

templates/base/entrance.html
{% extends "base/theme.html" %}
{% load staticfiles %}
{% load sitegate %}
{% block main_content %}

    <section id="services">
        <div class="container">
            <div class="row ">
                <div id="signin_form" class="col-lg-offset-3 col-lg-6 text-center">
                    <div class="my_signin_block">
                        <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign In</a></h2>
                        <h3 class="section-subheading text-muted">Welcome back!</h3>
                        {% sitegate_signin_form %}
                        <button id="btn_signup" class="btn btn-default btn-block btn-success" value="Sign Up" type="button">Join Yelp Knockoff</button>
                    </div>
                </div>
                <div id="signup_form" class="col-lg-offset-3 col-lg-6 text-center" style="display: none;">
                    <div class="my_signup_block">
                        <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Join Yelp Knockoff</a></h2>
                        <h3 class="section-subheading text-muted">Visit exotic places, and talk smack about them!</h3>
                        {% sitegate_signup_form %}
                        <button id="btn_signin" class="btn btn-default btn-block btn-success" value="Sign In" type="button">Sign in with an existing account</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block js_libs %}
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>
{% endblock %}

{% block bottom_js %}
    <script type="application/javascript">
            $(document).ready(function(){
                function toggle_signup(){
                    $('#signin_form').slideUp(function(){
                        $('#signup_form').slideDown();
                    });
                }

                function toggle_signin(){
                    $('#signup_form').slideUp(function(){
                        $('#signin_form').slideDown();
                    });
                }

                if ($('#signup_form').find('.has-error').size() > 0){
                    toggle_signup();
                }

                $('#btn_signup').click(function(){
                    toggle_signup();
                });

                $('#btn_signin').click(function(){
                    toggle_signin();
                })
            });
    </script>
{% endblock %}

templates/base/form.html
<!--{% extends "base/theme.html" %}
{% load widget_tweaks %}
{% block main_content %}
 <div class="header-buffer">
 </div>
 <section id="services">
 <div class="container">
<div class="row">
 {% if form %}
 <div class="col-md-12">
 <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}
 {% for field in form %}
 <div class="form-group warning">
 <label for="exampleInputFile">{{ field.label }}</label>
 {{ field|add_class:"form-control"}}
 {% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
 </div>
 {% if field.errors %}
 {% for error in field.errors %}
 <div class="alert alert-danger" id="error_{{ field.name }}">{{ error|escape }}</div>
 {% endfor %}
 {% endif %}

 {% endfor %}
 <input type="submit" class="btn btn-success" role="button" value="{{ verb|default:"Submit" }}" />
 </form>
</div>
{% endif %}
</div>
</div>
</section>
{% endblock %}-->

templates/base/rating.html
<!--<div class="coffeed-rating">
{% if rating == 1 %}
<i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 2 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 3 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 4 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i>
{% elif rating == 5 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i>
{% else %}
<i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% endif %}
</div>-->

templates/base/review.html
<!--<div class="row">
 <div class="col-md-8">
 <h2>{{ review.user.get_full_name }} <a class="subheading"> | {{ review.created_at | date }}</a></h2>
 </div>
 <div class="col-md-4 text-right">
 <h2>{% include 'base/rating.html' with rating=review.rating %}</h2>
 </div>
 
</div>
<p>{{ review.description }}</p>-->

templates/base/theme.html
{% extends "base/index.html" %}

{% block navigation %}
 <li>
 	<a class="page-scroll" href="/location">Find Coffee</a>
 </li>
  <li>
 	<a class="page-scroll" href="/location">Find Cocktails</a>
 </li>
 {% if request.user.is_authenticated %}
     <li>
        <a class="" href="#">({{ request.user.username }})</a>
     </li>
     <li>
         <a class="" href="/logout">Logout</a>
     </li>
 {% endif %}
{% endblock %}

{% block search %}
    {% comment %}
<form action="/search/" class="navbar-form navbar-right" method="get">
 <div class="form-group">
 <input type="text" placeholder="Search" class="form-control" name="query"></input>
 </div>
</form>
    {% endcomment %}
{% endblock %}
{% block main_content %}
{% endblock %}

templates/location/detail.html
{% extends "base/theme.html" %}
{%load staticfiles %}
{% block scripts %}
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{{ STATIC_URL }}theme/js/gmaps.js"></script>
    <script src="{{ STATIC_URL }}theme/js/maps.js"></script>
{% endblock %}
{% block main_content %}
    <div class="data-layer">
        <ul>
            <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}">{{ location.title }}</li>
        </ul>
    </div>
    <div class="header-buffer">
    </div>
    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="" >
                <div id="details">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12">
                                {% if location.fb_page %}
                                    <div id="fb-page-like-container" class="pull-left" style="width: 300px; margin-right: 20px;">
                                        <div class="fb-page" data-href="{{ location.fb_page }}" data-width="300"
                                             data-height="120" data-small-header="false" data-adapt-container-width="true"
                                             data-hide-cover="false" data-show-facepile="true" data-show-posts="true">
                                            <div class="fb-xfbml-parse-ignore">
                                                <blockquote cite="{{ location.fb_page }}"><a
                                                        href="{{ location.fb_page }}">{{ location.fb_page_label }}</a>
                                                </blockquote>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                {% comment %}
                                    <div class="fb-like" data-href="{{ fb_like_url }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                                {% endcomment %}
                                <div id="twitter-tweet-container" class="pull-left">
                                    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text={{ location.title|urlize }}" data-size="large">Tweet</a>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <h2>{{ location.title }}</h2>
                                {% if location.address %}<p><b>Location: </b>{{ location.address }}</b></p>{% endif %}
                                {% if location.hours %}<p><b>Opening Hours: </b>{{ location.hours }}</b></p>{% endif %}
                                <p><b>{{ location.description }}</b></p>
                            </div>
                            <div class="col-md-4">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">
                                    {% if location.image_file %}
                                        <div class="col-md-12 text-center">
                                            <img class="img-responsive" src="{{ location.image_file.url }}" style="width: 100%;" />
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        {% include 'location/specifics.html' with location=location %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 panel">
                                <div class="wide-map short-map" id="map"></div>
                                <div class="col-md-3"></div>
                                <div class="col-md-6 text-center">
                                    <br>
                                    {% if location.address %}<p>{{ location.address }}</p>{% endif %}
                                    {% if location.phone %}<p>{{ location.phone }}</p>{% endif %}
                                    {% if location.website %}<p><a href="{{ location.website }}">{{ location.website }}</a></p>{% endif %}
                                </div>
                                <div class="col-md-3"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
{% endblock %}

templates/location/list.html
{% extends "base/theme.html" %}
{%load staticfiles %}
{% load bootstrap_pagination %}
{% block main_content %}
    <div class="data-layer">
        <ul>
            {% for location in object_list %}
                <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</li>
            {% endfor %}
        </ul>
    </div>
    <div id="map" class="wide-map"></div>
    <div class="row">
        <div class="col-md-offset-2 col-md-3">
            {% if query or category >= 0 %}
                <div style="margin-top: 37px;">
                    <div class="form-group">
                        <h3>You Searched For:</h3>
                    </div>
                    <div class="form-group">
                        {% if query and category >= 0 %}
                            <span>"{{ query }}"</span>
                            <span> located in <strong>{{ category }}</strong></span>
                        {% elif query %}
                            <span>"{{ query }}"</span>
                        {% elif category >= 0 %}
                            <span> Shops in <strong>{{ category }}</strong></span>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-md-5">
            <div class="">
                <div class="form-group">
                    <form id="search_form" class="form-horizontal" method="GET" action="/search">
                        <div class="col-md-12">
                            <h3>Filter Results</h3>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6" style="padding-right: 0px;">
                                        <input type="text" id="id_query" placeholder="Search" class="form-control" name="query" value="{{ request.GET.query|default:"" }}"/>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="id_category" class="control-label col-md-2">Or</label>
                                        <div class="col-md-10">
                                            <select id="id_category" name="category" class="form-control">
                                                <option value="" {% if request.GET.category == "" %}selected{% endif %}>By area..</option>
                                                <option value="0" {% if request.GET.category == "0" %}selected{% endif %}>Botley</option>
                                                <option value="1" {% if request.GET.category == "1" %}selected{% endif %}>Central</option>
                                                <option value="2" {% if request.GET.category == "2" %}selected{% endif %}>Cowley</option>
                                                <option value="3" {% if request.GET.category == "3" %}selected{% endif %}>Headington</option>
                                                <option value="4" {% if request.GET.category == "4" %}selected{% endif %}>Jericho</option>
                                                <option value="5" {% if request.GET.category == "5" %}selected{% endif %}>Summertown</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--<button name="area-filter">Filter results</button>-->
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row main-content">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="location-grid">
                {% for location in object_list %}
                    <div class="grid-item">
                        <div class='row'>
                            <div class="col-md-12 grid-item-content">
                                <div class="location-details-container">
                                    <h3><a href=" {{ location.get_absolute_url }}">{{ location.title }}</a></h3>
                                    {% if location.area >= 0 %}<p><b>Location: </b>{{ location.get_area_display }}</p>{% endif %}
                                    {% if location.hours %}<p><b>Opening Hours: </b>{{ location.hours }}</p>{% endif %}
                                    <p><b>{{ location.description|truncatewords:32 }}</b></p>
                                </div>
                                <div class="location-details-spacer"></div>
                                <div class="location-img-container">
                                    {% if location.image_file %}
                                        <img class="img-responsive" src="{{ location.image_file.url }}" /><br><br><br>
                                    {% else %}
                                        <img class="img-responsive" src="{% static "img/location-placeholder.png" %}" /><br><br><br>
                                    {% endif %}
                                </div>
                                {% comment %}
                                {% if location.image_file %}
                                    <img class="img-responsive" src="{{ location.image_file.url }}"></img><br><br><br>
                                {% endif %}
                                {% endcomment %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% comment %}
            {% for location in object_list %}
                <div class='row'>
                    <div class="col-md-8">
                        <h3><a href=" {{ location.get_absolute_url }}">{{ location.title }}</a></h3>
                        {% if location.area >= 0 %}<p><b>Location: </b>{{ location.get_area_display }}</p>{% endif %}
                        {% if location.hours %}<p><b>Opening Hours: </b>{{ location.hours }}</p>{% endif %}
                        <p><b>{{ location.description }}</b></p>

                        {% if location.image_file %}
                            <img class="img-responsive" src="{{ location.image_file.url }}"></img><br><br><br>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
            {% endcomment %}
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}
{% block pagination %}
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}
{% block bottom_js %}
    <script type="application/javascript">
        $(document).ready(function(){
            $('#id_category, #id_query').change(function(){
                $('#search_form').submit();
            });

            $('.location-grid').isotope({
                // options
                itemSelector: '.grid-item',
                layoutMode: 'fitRows',
                fitRows: {
                    gutter: 10
                }
            });
        });
    </script>
{% endblock %}

templates/location/specifics.html
<div class="row">
<div class="col-md-4">
 
<p><b>Area: </b>{% if location.area %}{{ location.get_area_display }}{% else %}----{% endif %}</p>
<p><b>WiFi: </b>{% if location.wifi %}{{ location.get_wifi_display }}{% else %}----{% endif %}</p>
</div>
<div class="col-md-4">
<p><b>Seating: </b>{% if location.seating %}{{ location.get_seating_display }}{% else %}----{% endif %}</p>
<p><b>Outdoor Seating: </b>{% if location.outdoor %}{{ location.get_outdoor_display }}{% else %}----{% endif %}</p>
</div>
</div>